---
abstract: 'Add color to the output of any command'
author:
  - 'Andrew Sterling Hanenkamp <hanenkamp@cpan.org>'
build_requires:
  File::Temp: '0'
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.019, CPAN::Meta::Converter version 2.141520'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: App-Colorist
requires:
  Carp: '0'
  IO::Handle: '0'
  IO::Select: '0'
  IPC::Open3: '0'
  Moose: '0'
  Moose::Exporter: '0'
  MooseX::Getopt: '0'
  POSIX: '0'
  Readonly: '0'
  Scalar::Util: '0'
  YAML: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=App-Colorist
  repository: git://github.com/zostay/App-Colorist.git
version: '0.141730'
